version: '3.8'
services:
  postgres:
    container_name: fbpostgres
    image: postgres:16-bookworm
    restart: always
    env_file: .env
    ports:
      - '5433:5432'
    volumes:
      - fastbasedb:/var/lib/postgresql/data
  redis:
    container_name: fbredis
    image: redis/redis-stack
    restart: always
    ports:
      - '6380:6379'
      - '6381:8001'
volumes:
  fastbasedb: