[tool.poetry]
name = "fastauth"
version = "0.1.0"
description = ""
authors = ["enchance <enchance@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
sqlmodel = "^0.0.11"
firebase-admin = "^6.2.0"
python-decouple = "^3.8"
asyncpg = "^0.29.0"

[tool.poetry.group.dev.dependencies]
icecream = "^2.1.3"
pytest = "^7.4.3"
pytest-sugar = "^0.9.7"
pytest-asyncio = "^0.21.1"
factory-boy = "^3.3.0"
freezegun = "^1.2.2"
alembic = "^1.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
