"""empty message

Revision ID: 3d9db22bf2dc
Revises: 
Create Date: 2023-12-04 14:50:54.946589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                 # New
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d9db22bf2dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=199), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=199), nullable=True),
    sa.Column('groups', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_role')
    op.drop_table('auth_group')
    # ### end Alembic commands ###
