"""user tbl

Revision ID: d031c82c802a
Revises: 3d9db22bf2dc
Create Date: 2023-12-04 14:52:30.006185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                 # New
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd031c82c802a'
down_revision: Union[str, None] = '3d9db22bf2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=190), nullable=False),
    sa.Column('display', sqlmodel.sql.sqltypes.AutoString(length=199), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=190), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('groups', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_user')
    # ### end Alembic commands ###
